name: Check PR

on:
  pull_request:
    branches:
        - main

jobs:
  main_job:
    name: Check PR
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install volta
      uses: volta-cli/action@v4

    - name: Clean Install dependencies
      run: npm ci

    - name: Run Linting
      run: npm run lint

    - name: Run TypeScript Type Checker
      run: npx tsc --noEmit
  
    - name: Copy sample configuration file
      run: node -e "require('fs').copyFileSync('config.example.yml', 'config.yml');"

    - name: Run tests
      run: npm test -- --silent --coverage

    - name: Upload coverage to GitHub Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage/lcov.info